spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/iresearch?characterEncoding=utf-8&allowMultiQueries=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    time-zone: Asia/Shanghai

  redis:
    host: localhost
    port: 6378
    database: 0


logging:
  config: classpath:logback-spring.xml


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
